### ISSUE TITLE
Error on first npm start

### ISSUE THREAD

**Issue by tcase** [mrmarkwell/evergreendb#48]
> evergreendb@0.1.0 start C:\Users\Travis\Documents\GitHub\evergreendb\electron
> electron .

App threw an error during load
Error: ENOENT: no such file or directory, open 'C:\Users\Travis\AppData\Roaming\evergreendb\Settings'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1233:33)
    at Object.writeFileSync (C:\Users\Travis\Documents\GitHub\evergreendb\electron\node_modules\jsonfile\index.js:115:13)
    at Settings._ensureSettings (C:\Users\Travis\Documents\GitHub\evergreendb\electron\node_modules\electron-settings\lib\settings.js:134:18)
    at Settings._readSettings (C:\Users\Travis\Documents\GitHub\evergreendb\electron\node_modules\electron-settings\lib\settings.js:173:10)
    at Settings._setValueAtKeyPath (C:\Users\Travis\Documents\GitHub\evergreendb\electron\node_modules\electron-settings\lib\settings.js:242:18)
    at Settings.set (C:\Users\Travis\Documents\GitHub\evergreendb\electron\node_modules\electron-settings\lib\settings.js:348:10)
    at Object.<anonymous> (C:\Users\Travis\Documents\GitHub\evergreendb\electron\main.js:9:10)
    at Object.<anonymous> (C:\Users\Travis\Documents\GitHub\evergreendb\electron\main.js:74:3)

**Comment by jacksondburnette** [comment]
Apparently you have to wait for the app to be "ready" before you start trying to use it. Addressed in PR #52

I'm really glad this got caught, this could have lurked until we actually tried to install it on a real user's system. How embarrassing

Thanks Travis 😃

**Comment by jacksondburnette** [comment]
PR #52 closed
